langchain4j:
#  community:
#    dashscope:
#      chat-model:
#        api-key: ${DASHSCOPE_APIKEY}
##        model-name: qwen-max
##        model-name: qwen-plus
#        model-name: qwen-max-latest

  ollama:
    chat-model:
      base-url: http://127.0.0.1:11434
      model-name: qwen3:1.7b
